// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	AddNumber(ctx context.Context, number string) (Number, error)
	GetNumbers(ctx context.Context) ([]Number, error)
}

var _ Querier = (*Queries)(nil)
